# Generated by Django 3.2.9 on 2022-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_degree',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('MS', 'MS'), ('MD', 'MD'), ('BAMS', 'BAMS'), ('BHMS', 'BHMS')], max_length=255, null=True),
        ),
    ]
