# Generated by Django 3.2.9 on 2022-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
    ]
