# Generated by Django 3.2.9 on 2022-06-07 05:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32140)),
                ('hospital_address', models.CharField(blank=True, max_length=400, null=True)),
                ('hospital_rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
