# Generated by Django 3.2.9 on 2022-06-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
