# Generated by Django 3.2.9 on 2022-06-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20220607_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='city_name',
            new_name='hopital_state',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='state_name',
            new_name='hospital_city',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='phone_no',
            new_name='hospital_phone',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='pin_code',
            new_name='hospital_pin',
        ),
    ]
