# Generated by Django 3.2.9 on 2022-06-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_hospital_hospital_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hopital_state',
            new_name='hospital_state',
        ),
    ]
