# Generated by Django 3.2.9 on 2022-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_rename_hopital_state_hospital_hospital_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_about',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
