# Generated by Django 3.2.9 on 2022-05-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=255, unique=True)),
                ('disease_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('disease_precaution1', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_precaution2', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_precaution3', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_precaution4', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialities.speciality')),
            ],
        ),
    ]
